### ISSUE TITLE
Windows builds

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/r-rgdal-feedstock#1]
I guess we need something like https://github.com/conda-forge/r-ncdf4-feedstock/pull/4

**Comment by ocefpaf** [comment]
@mingwandroid do you have any advice for us here? If we need mingw builds of all gdal and its dependencies I don't see this happening anything soon :-(

Maybe we have an alternative?

**Comment by mingwandroid** [comment]
Well we can get such things from msys2 again if that's what we decide is best.

**Comment by ocefpaf** [comment]
> Well we can get such things from msys2 again if that's what we decide is best.

I was hoping you would tell me what is best. (IMO the best approach is the easiest one to implement and maintain. Is it possible to use the `gdal` we have? I tried in #8 and failed miserably!)

**Comment by ocefpaf** [comment]
@mingwandroid take a look at how painful it is today to install a geospatial stack without conda: https://datacarpentry.org/geospatial-workshop/setup.html

If we can get `r-rgdal` working on Windows we could simplify all that to a simple conda environment file.

**Comment by ocefpaf** [comment]
I went with the repackaged version. Not ideal but solved the problem. Thanks @mingwandroid.
